# Generated by Django 3.0.5 on 2020-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='src',
            field=models.FileField(null=True, upload_to='mediafiles/'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Текст блога'),
        ),
    ]
