# Generated by Django 3.0.5 on 2020-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200501_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='src',
            field=models.FileField(null=True, upload_to='posts/'),
        ),
    ]
